# Site settings
title: G2 PLAZA
email: buin2009@gmail.com
author: buin2009
description: "Nhiều sản phẩm giảm giá mỗi ngày, kênh thông tin mua sắm"
baseurl: ""
url: "http://buin2009.github.io"
google_analytics: UA-34305400-1
animated: false

# Build settings
markdown: kramdown
permalink: none
paginate: 5
sass:
  compressed: true

gems:
  - jekyll-sitemap  

