# Site settings
title: a Jekyll theme using BASSCSS
email: buin2009@gmail.com
author: buin2009
description: "A simple, beautiful theme for Jekyll that emphasizes content rather than aesthetic fluff."
baseurl: ""
url: "http://buin2009.github.com"
google_analytics: UA-34305400-1
animated: false

# Build settings
markdown: kramdown
permalink: none
paginate: 3
sass:
  compressed: true

